<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html>
<head>
<meta name="copyright" content="2000,  Bradley Kjell" />
<meta name="author" content="Bradley Kjell kjell@ieee.org " />
<meta name="translation" content="Copyright 2004 Deutsche &Uuml;bersetzung Heinrich Gailer heinrich@gailer-net.de" />
<meta name="robots" content="index,follow" />
<title>M&ouml;gliche Ausnahmen</title>
<link rel="stylesheet" type="text/css" href="../CAIstyle.css" />
</head>

<body>
<!-- generated by CSSmaker.java, version of 10/12/2004-->
<!-- from source javaChap80.frames on Thu Sep 11 15:46:28 CEST 2008 -->

<!-- ANSWER AREA -->


<div class="answer">
<h3>Eine gute Antwort w&auml;re:</h3>
<p>
Die <code>catch{}</code>-Bl&ouml;cke sind in der richtigen Reihenfolge,
da <code>ArithmeticException</code> weder ein
Vorfahre noch ein Nachkomme von
<code>NumberFormatException</code> ist.
Die andere Reihenfolge der zwei Bl&ouml;cke w&uuml;rde ebenso funktionieren.
</p>

</div>

<!-- LESSON AREA -->
<div class="lesson">
<h1>M&ouml;gliche Ausnahmen</h1>
<p>
In dem Beispielprogramm
k&ouml;nnte der <code>try{}</code>-Block
(1) eine <code>IOException</code>,
(2) eine <code>NumberFormatException</code>
oder
(3) eine <code>ArithmeticException</code> ausl&ouml;sen.
</p>

<pre class="program">
  public static void main ( String[] a ) <span style="font-weight:bold">throws IOException</span>
     . . . .

    <span style="color:blue;font-weight:bold">try
    {</span>
      System.out.println("Geben Sie den Zaehler ein:");
      inData = stdin.readLine();
      zahl    = Integer.parseInt( inData );

      System.out.println("Geben Sie den Divisor ein:");
      inData = stdin.readLine();
      div    = Integer.parseInt( inData );

      System.out.println( zahl + " / " + div + " ist " + (zahl/div) );
    <span style="color:blue;font-weight:bold">}</span>
    <span style="color:blue;font-weight:bold">catch (NumberFormatException ex )
    {</span>
      . . .
    <span style="color:blue;font-weight:bold">}</span>

    <span style="color:blue;font-weight:bold">catch (ArithmeticException ex )
    {</span>
      . . .
    <span style="color:blue;font-weight:bold">}</span>
  }
</pre>


<p>
Eine <code>IOException</code> k&ouml;nnte bei jeder <code>readLine()</code> Anweisung auftreten.
Es gibt keinen <code>catch{}</code>-Block f&uuml;r diesen Typ von Ausnahme,
also muss die Methode sagen <code>throws IOException</code>.
</p>

<p>
Eine <code>NumberFormatException</code> k&ouml;nnte bei jedem Aufruf der
<code>parseInt()</code> auftreten.
Der erste <code>catch{}</code>-Block ist f&uuml;r diesen Typ von Ausnahme.
Er wird Ausnahmen auffangen, die von jedem <code>parseInt()</code> ausgel&ouml;st werden.
</p>

<p>
Ein <code>ArithmeticException</code> k&ouml;nnte auftreten,
wenn der Anwender Daten eingibt, die
f&uuml;r eine Integer Division nicht erlaubt sind.
Der zweite <code>catch{}</code>-Block ist f&uuml;r diesen Typ von Ausnahmen.
</p>


</div>

<!-- QUESTION AREA -->
<div class="question">
<h3> FRAGE 13:</h3>
<a href="ch80_14.html">
<img src="../nextBut.gif" hspace="5" align="right" border="0"/></a>
<p>
Welcher Typ von Ausnahme wird ausgel&ouml;st, wenn der Anwender f&uuml;r den Divisor eine 0 eingibt?
</p>

</div>
<div>
<a title="Zurück zum Inhaltsverzeichnis gehen." href="../../java-toc.html#80">Inhaltsverzeichnis</a>
</div>

</body>
</html>
