<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html>
<head>
<meta name="copyright" content="2000,  Bradley Kjell" />
<meta name="author" content="Bradley Kjell kjell@ieee.org " />
<meta name="translation" content="Copyright 2004 Deutsche &Uuml;bersetzung Heinrich Gailer heinrich@gailer-net.de" />
<meta name="robots" content="index,follow" />
<title>Der finally{}-Block</title>
<link rel="stylesheet" type="text/css" href="../CAIstyle.css" />
</head>

<body>
<!-- generated by CSSmaker.java, version of 10/12/2004-->
<!-- from source javaChap80.frames on Thu Sep 11 15:46:28 CEST 2008 -->

<!-- ANSWER AREA -->
<p>
Wenn eine <code>IOException</code> in dem <code>try{}</code>-Block auftritt,
was passiert?
</p>

<div class="answer">
<h3>Eine gute Antwort w&auml;re:</h3>
<p>
Die Ausf&uuml;hrung dieser Methode wird beendet und die Methode
gibt eine <code>IOException</code> an den Aufrufer zur&uuml;ck.
</p>


</div>

<!-- LESSON AREA -->
<div class="lesson">
<h1>Der <code><strong>finally{}</strong></code>-Block</h1>

<A NAME="finally block"></A>
<p>
Wenn eine <code>IOException</code> in diesem Programm auftritt, verliert es sofort die Kontrolle.
Die Ausnahme wird an die Methode weitergereicht, die sie aufgerufen hat.
In diesem Fall das Java Laufzeit System.
Die Ausf&uuml;hrung wird f&uuml;r dieses Programm beendet.
</p>

<p>
Durch die Verwendung eines <code>finally{}</code>-Blocks k&ouml;nnen Sie sicherstellen,
dass bestimmte Anweisungen immer ausgef&uuml;hrt werden,
egal wie der <code>try{}</code>-Block verlassen wurde.
Hier ist die <code>try/catch/finally{}</code>-Struktur.
</p>

<pre class="program">
try
{
  // Anweisungen von denen einige
  // Ausnahmen ausl&ouml;sen k&ouml;nnten
}

catch ( <em>IrgendeinExceptionTyp</em> ex )
{
  // Anweisungen, um diesen Typ von Ausnahmen zu handhaben
}


....  // weitere catch-Bl&ouml;cke

catch ( <em>EinWeitererExceptionTyp</em> ex )
{
  // Anweisungen, um diesen Typ von Ausnahmen zu handhaben
}

<span style="color:blue;font-weight:bold">finally
{</span>
  // Anweisungen, die ausgef&uuml;hrt werden
  // egal wie der try-Block verlassen wurde.
<span style="color:blue;font-weight:bold">}</span>

// weitere Anweisungen nach der Struktur

</pre>


<p>
Es kann nur einen <code>finally{}</code>-Block geben und er muss
auf die <code>catch{}</code>-Bl&ouml;cke folgen.
</p>

<ol>
<li>
Wenn der <code>try{}</code>-Block normal verlassen wird (es sind keine Ausnahmen aufgetreten), dann
geht die Kontrolle direkt an den
<code>finally{}</code>-Block.
Nach dem <code>finally{}</code>-Block bekommen die Anweisungen, die auf die Struktur folgen, die Kontrolle.
</li>

<li>
Wenn der <code>try{}</code>-Block auf Grund einer Ausnahme verlassen wird,
die von einem <code>catch{}</code>-Block behandelt wird,
wird zuerst dieser Block ausgef&uuml;hrt und <strong>dann</strong>
geht die Kontrolle an den
<code>finally{}</code>-Block.
Nach dem <code>finally{}</code>-Block bekommen die Anweisungen, die auf die Struktur folgen, die Kontrolle.                                                              </li>

<li>
Wenn der <code>try{}</code>-Block auf Grund einer Ausnahme verlassen wird,
die <strong>nicht</strong> von einem
<code>catch{}</code>-Block behandelt wird,
geht die Kontrolle direkt an den
<code>finally{}</code>-Block.
Nachdem der <code>finally{}</code>-Block ausgef&uuml;hrt ist,
wird die Ausnahme an den Aufrufer zur&uuml;ckgegeben und es wird die Kontrolle
an den Aufrufer zur&uuml;ckgegeben.
</li>

</ol>


</div>

<!-- QUESTION AREA -->
<div class="question">
<h3> FRAGE 15:</h3>
<a href="ch80_16.html">
<img src="../nextBut.gif" hspace="5" align="right" border="0"/></a>
<p>
Wird der <code>finally{}</code>-Block immer ausgef&uuml;hrt?
</p>

</div>
<div>
<a title="Zurück zum Inhaltsverzeichnis gehen." href="../../java-toc.html#80">Inhaltsverzeichnis</a>
</div>

</body>
</html>
