<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html>
<head>
<meta name="copyright" content="2000,  Bradley Kjell" />
<meta name="author" content="Bradley Kjell kjell@ieee.org " />
<meta name="translation" content="Copyright 2004 Deutsche &Uuml;bersetzung Heinrich Gailer heinrich@gailer-net.de" />
<meta name="robots" content="index,follow" />
<title>Stack-Protokoll</title>
<link rel="stylesheet" type="text/css" href="../CAIstyle.css" />
</head>

<body>
<!-- generated by CSSmaker.java, version of 10/12/2004-->
<!-- from source javaChap80.frames on Thu Sep 11 15:46:29 CEST 2008 -->

<!-- ANSWER AREA -->
<pre class="code">
Geben Sie den Zaehler ein:
Unsinn
Wenn die Division nicht funktioniert hat, haben Sie falsche Daten eingeben.
Exception in thread "main" java.lang.NumberFormatException: Unsinn
        at java.lang.Integer.parseInt(Integer.java:409)
        at java.lang.Integer.parseInt(Integer.java:458)
        at FinallyUebung.main(FinallyUebung.java:16)
</pre>

<p>
Der <code>try{}</code>-Block hat eine Ausnahme vom Typ <code>NumberFormatException</code> ausgel&ouml;st,
aber es gab keinen <code>catch{}</code>-Block daf&uuml;r.
Also: (1) wurde der <code>finally</code>-Block ausgef&uuml;hrt und dann
(2) wurde die Ausnahme an den Aufrufer zur&uuml;ckgegeben (in diesem Fall das Java Laufzeitsystem), das (3) die letzten vier Zeilen ausgegeben hat.
</p>

</ANSWER>


<div class="answer">
</div>

<!-- LESSON AREA -->
<div class="lesson">
<h1>Stack-Protokoll</h1>
<A NAME="stack trace"></A>
<p>
Die letzten vier Zeilen werden ein <b>Stack-Protokoll</b> genannt.
Sie werden nachher sehen wie Sie sie ausgeben k&ouml;nnen ohne das Programm zu stoppen.
Hier ist ein Teil des Programms:
</p>

<pre class="program">
    <span style="color:blue;font-weight:bold">try
    {</span>
      System.out.println("Geben Sie den Zaehler ein:");
      ...
      System.out.println("Geben Sie den Divisor ein:");
      ...
      System.out.println( zahl + " / " + div + " ist " + (zahl/div) );
    <span style="color:blue;font-weight:bold">}</span>

    <span style="color:blue;font-weight:bold">catch ( ArithmeticException ex )
    {</span>
      System.out.println
        ("Sie koennen  " + zahl + " nicht durch " + div + " dividieren");
    <span style="color:blue;font-weight:bold">}</span>

    <span style="color:red;font-weight:bold">finally
    {</span>
      System.out.println
        ("Wenn die Division nicht funktioniert hat,
          haben Sie falsche Daten eingeben."        );
    <span style="color:red;font-weight:bold">}</span>

    System.out.println("Good-bye" );
</pre>


<p>
Hier sind weitere Beispiele von Output:
</p>

<blockquote>
Output 1:

<pre class="code">
Geben Sie den Zaehler ein:
26
Geben Sie den Divisor ein:
4
26 / 4 is 6
Wenn die Division nicht funktioniert hat, haben Sie falsche Daten eingeben.
Good-bye
</pre>


Output 2:

<pre class="code">
Geben Sie den Zaehler ein:
26
Geben Sie den Divisor ein:
0
Sie koennen 26 nicht durch 0 dividieren
Wenn die Division nicht funktioniert hat, haben Sie falsche Daten eingeben.
Good-bye
</pre>


Output 3:

<pre class="code">
Geben Sie den Zaehler ein:
26
Geben Sie den Divisor ein:
Zero
Wenn die Division nicht funktioniert hat, haben Sie falsche Daten eingeben.
Exception in thread "main" java.lang.NumberFormatException: Zero
        at java.lang.Integer.parseInt(Integer.java:409)
        at java.lang.Integer.parseInt(Integer.java:458)
        at FinallyUebung.main(FinallyUebung.java:19)
</pre>




</div>

<!-- QUESTION AREA -->
<div class="question">
<h3> FRAGE 18:</h3>
<a href="ch80_19.html">
<img src="../nextBut.gif" hspace="5" align="right" border="0"/></a>
<form name="f">
<table border bordercolor="blue" cellpadding="5" bgcolor="white">
<tr>
<td width="80%">
Bei welchem Output f&uuml;hrte der <code>try{}</code>-Block zu keiner
Ausnahme?
</td>
<td>
<input type=button value="  ?  " name="ButA"
onClick="f.TextA.value='1'">
<input type=text size="8" name="TextA">
</td>
</tr>

<tr>
<td>
Bei welchem Output hat der <code>try{}</code>-Block eine Ausnahme
vom Typ <code>ArithmeticException</code> ausgel&ouml;st?
</td>
<td>
<input type=button value="  ?  " name="ButB"
onClick="f.TextB.value='2'">
<input type=text size="8" name="TextB">
</td>
</tr>

<tr>
<td>
Bei welchem Output hat der <code>try{}</code>-Block eine unbehandelte<br /> Ausnahme ausgel&ouml;st (eine ohne <code>catch{}</code>-Block)?
</td>
<td>
<input type=button value="  ?  " name="ButC"
onClick="f.TextC.value='3'">
<input type=text size="8" name="TextC">
</td>
</tr>

<tr>
<td>
Bei welchem Output wurde der <code>finally{}</code>-Block ausgef&uuml;hrt?
</td>
<td>
<input type=button value="  ?  " name="ButD"
onClick="f.TextD.value='1, 2, 3'">
<input type=text size="8" name="TextD">
</td>
</tr>
</table>

</div>
<div>
<a title="Zurück zum Inhaltsverzeichnis gehen." href="../../java-toc.html#80">Inhaltsverzeichnis</a>
</div>

</body>
</html>
